import type { Metadata } from "next";
import { Jost } from "next/font/google";
import { Providers } from "./providers";

import "./globals.css";

const jost = Jost({ weight: ["400", "500", "600", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
